name: 一个阉人的真实故事
description: 一个阉人的真实故事，手术过后后悔的一些远古记录
curator: ''
source: ''
tags:
- 生命故事
- 个人经历
- 社会环境
- 转变故事
- 真实记录
license: ''
files:
- name: '1'
  filename: 1.png
  type: image
  format: PNG Image
  size: 632757
  md5: 38afcbe6af82887a0ed9a6676fa5feda
  page: 1.png
- name: '10'
  filename: 10.png
  type: image
  format: PNG Image
  size: 565096
  md5: 68a2f3c52c79851c51f29a6817cc0e0b
  page: 10.png
- name: '11'
  filename: 11.png
  type: image
  format: PNG Image
  size: 510304
  md5: f591b1b9677d5749b1e24c71784bfe73
  page: 11.png
- name: '12'
  filename: 12.png
  type: image
  format: PNG Image
  size: 606510
  md5: d3b4d6387d1379a1bb18706889db7301
  page: 12.png
- name: '13'
  filename: 13.png
  type: image
  format: PNG Image
  size: 667551
  md5: 14d10b98aa5e3fa103b76c950ae49161
  page: 13.png
- name: '14'
  filename: 14.png
  type: image
  format: PNG Image
  size: 601615
  md5: fbf42d5d45f5a42e46c4e2c954017caf
  page: 14.png
- name: '15'
  filename: 15.png
  type: image
  format: PNG Image
  size: 517826
  md5: 48a4cfcd2c79466a3cecc6eda1fc1efb
  page: 15.png
- name: '16'
  filename: 16.png
  type: image
  format: PNG Image
  size: 533103
  md5: 2511e3b36d8ca57570a3d2a1226801f4
  page: 16.png
- name: '17'
  filename: 17.png
  type: image
  format: PNG Image
  size: 709503
  md5: 56b8b76ac4f43097b694e68dc1a8078b
  page: 17.png
- name: '18'
  filename: 18.png
  type: image
  format: PNG Image
  size: 493468
  md5: 750443b1e9cfd7c8ec55d93360ad7ced
  page: 18.png
- name: '19'
  filename: 19.png
  type: image
  format: PNG Image
  size: 512493
  md5: efd00f2f1ad8ab1ae4262f2f28f30594
  page: 19.png
- name: '2'
  filename: 2.png
  type: image
  format: PNG Image
  size: 533687
  md5: 4071e51f59890a4e1b22bd16088cecf2
  page: 2.png
- name: '20'
  filename: 20.png
  type: image
  format: PNG Image
  size: 535226
  md5: e4ad6bfe5e17a187f94b322cd18e15c1
  page: 20.png
- name: '21'
  filename: 21.png
  type: image
  format: PNG Image
  size: 745552
  md5: 865d600b9b3a2cf821f40c6d9df65ea5
  page: 21.png
- name: '22'
  filename: 22.png
  type: image
  format: PNG Image
  size: 526588
  md5: d9aadb8c3625c2fd868dec479a8a14dd
  page: 22.png
- name: '23'
  filename: 23.png
  type: image
  format: PNG Image
  size: 525239
  md5: 3b4290d2bf6064c027196ec0811bb32e
  page: 23.png
- name: '24'
  filename: 24.png
  type: image
  format: PNG Image
  size: 561864
  md5: 88601511d2ffb092ce8b30cca6cf2911
  page: 24.png
- name: '25'
  filename: 25.png
  type: image
  format: PNG Image
  size: 682433
  md5: 061c765b3447f4afa29687da90a94681
  page: 25.png
- name: '26'
  filename: 26.png
  type: image
  format: PNG Image
  size: 505249
  md5: 02e8fe3db2d5611a4b11f830208fe0f5
  page: 26.png
- name: '27'
  filename: 27.png
  type: image
  format: PNG Image
  size: 459710
  md5: f524cb1f01a6d741c95eac8e134c2f7c
  page: 27.png
- name: '28'
  filename: 28.png
  type: image
  format: PNG Image
  size: 493011
  md5: 255200188bd5e29235ccb395ac285193
  page: 28.png
- name: '29'
  filename: 29.png
  type: image
  format: PNG Image
  size: 613615
  md5: c1623f13b0ab298ecae9085c208fb10c
  page: 29.png
- name: '3'
  filename: 3.png
  type: image
  format: PNG Image
  size: 373072
  md5: b12c8cf221565f9d5a21e4630061219c
  page: 3.png
- name: '30'
  filename: 30.png
  type: image
  format: PNG Image
  size: 581126
  md5: b7c077a541c566851686cd9ecd26fc01
  page: 30.png
- name: '35'
  filename: 35.png
  type: image
  format: PNG Image
  size: 566546
  md5: e3d433c32a7f0277195d81fb92000623
  page: 35.png
- name: '36'
  filename: 36.png
  type: image
  format: PNG Image
  size: 756189
  md5: 17a8ae2131b35ee8e52b39a185cfddb7
  page: 36.png
- name: '38'
  filename: 38.png
  type: image
  format: PNG Image
  size: 523096
  md5: d8d6d495a8d76db4eca55152d4d8d4ff
  page: 38.png
- name: '39'
  filename: 39.png
  type: image
  format: PNG Image
  size: 535290
  md5: cf9eb97fbbc4c836d13d6bba4b9d8ca0
  page: 39.png
- name: '4'
  filename: 4.png
  type: image
  format: PNG Image
  size: 511925
  md5: 7ae9b3d5734ee0114905a609ce13aaf7
  page: 4.png
- name: '40'
  filename: 40.png
  type: image
  format: PNG Image
  size: 694453
  md5: 740ee35d9d2653290bf935ab04887132
  page: 40.png
- name: '41'
  filename: 41.png
  type: image
  format: PNG Image
  size: 476563
  md5: 51ddd47c9e47b405792c3813d2f58803
  page: 41.png
- name: '42'
  filename: 42.png
  type: image
  format: PNG Image
  size: 532455
  md5: 14bb81a680576349ea896540ccb92102
  page: 42.png
- name: '43'
  filename: 43.png
  type: image
  format: PNG Image
  size: 514279
  md5: 8881677f785072bcd05adbd947e20567
  page: 43.png
- name: '44'
  filename: 44.png
  type: image
  format: PNG Image
  size: 649619
  md5: 360dbd7cd3db5c8111081d7d92bef5c6
  page: 44.png
- name: '45'
  filename: 45.png
  type: image
  format: PNG Image
  size: 487059
  md5: 5842b9b4f076b6e4c56acd34e05f31c8
  page: 45.png
- name: '5'
  filename: 5.png
  type: image
  format: PNG Image
  size: 571481
  md5: c59b06b5b09b7a684a527118f06e1224
  page: 5.png
- name: '6'
  filename: 6.png
  type: image
  format: PNG Image
  size: 382280
  md5: 65566a17dc80d47e80bfb60ff2608e85
  page: 6.png
- name: '7'
  filename: 7.png
  type: image
  format: PNG Image
  size: 448992
  md5: 022eab0d9983adaa139eccdf877efc06
  page: 7.png
- name: '8'
  filename: 8.png
  type: image
  format: PNG Image
  size: 359781
  md5: 10d14df4b6f84ee433f14a748965a15c
  page: 8.png
- name: '9'
  filename: 9.png
  type: image
  format: PNG Image
  size: 623488
  md5: 18b3362b8f8f129268f8a1f1512e47d4
  page: 9.png
subdirs: []
