name: 学术文献
description: 此目录包含关于跨性别议题的学术文献，包括人文、医学、法律和社会科学领域的研究和资料，包括但不限于发表于学术期刊的论文和由大学附属出版社出版的学术书籍。采用近似于学术写作的风格创作、发布于某些期刊杂志，但不确定是否为「学术」文献的，放置于「杂志及新闻报道」分类。
curator: ''
source: ''
tags:
- 跨性别
- 学术文献
- 人文
- 医学
- 法律
- 社会科学
license: ''
files: []
subdirs:
- 人文社科
- 医学
- 法律
