name: 《银荆的告白》插画
description: 本目录包含《银荆的告白》系列插画，展示了跨性别主题下的文学创作与艺术表现。该系列小说通过生动的插图补充了故事内容，增强了读者对角色与情节的理解。
curator: ''
source: ''
tags:
- 文学作品
- 艺术创作
- 跨性别主题
- 插画
- 《银荆的告白》
license: ''
files: []
subdirs:
- 第一卷
- 第三卷
- 第二卷
- 第五卷
- 第四卷
