.:
  name: .
  description: 跨性别与多元性别档案馆包含如下内容：
学术文献:
  name: 学术文献
  description: 此目录包含关于跨性别议题的学术文献，包括人文、医学、法律和社会科学领域的研究和资料，包括但不限于发表于学术期刊的论文和由大学附属出版社出版的学术书籍。采用近似于学术写作的风格创作、发布于某些期刊杂志，但不确定是否为「学术」文献的，放置于「杂志及新闻报道」分类。
学术文献/人文社科:
  name: 人文社科
  description: 该目录下收录了与跨性别相关的社会科学研究文献，包括对跨性别群体的社会分析、文化研究以及相关的理论探讨。这些文献旨在提升对跨性别群体生活现状的理解与关注。
学术文献/医学:
  name: 医学
  description: '该目录包含了多篇与跨性别和变性医疗相关的学术文献，主要涉及变性人与其所在社会的医疗、法律、伦理等多方面的互动与现状。这些研究揭示了跨性别群体在医疗过程中所遭遇的诸多挑战，包括医疗服务的质量、社会歧视、法律支持缺失等问题，强调了人性化医疗的重要性与必要性。


    冯泽永的研究文章深入探讨了变性人的手术态度以及手术后所面临的社会心理压力，强调了尊重变性人的自主选择与提供良好支持的重要性。医师报的文章则分析了变性手术领域内存在的法规与监管缺失问题，呼吁加强对变性者的合法权益保护。


    中国跨性别男男性行为者的HIV感染风险研究和2018年爱滋病预防项目调查报告中，进一步揭示了跨性别群体在性健康方面的脆弱性，暴露了社会支持体系的不完善及相关健康服务的缺失。整体上，这些文献不仅探讨了医学与伦理问题，还反映了法律和社会环境对跨性别群体生存现状的影响，提供了大量的数据支持和见解，期望改变现行医疗体系中的不足之处。


    本目录的文献涵盖了主题广泛的医疗研究，重复强调了多元性别友善医疗的重要性，以及法律和社会对跨性别身份的影响。这些研究为政策制定者提供了宝贵的数据，助力推动相关法律改进，实现对变性人和跨性别群体的全面支持与保障。'
学术文献/法律:
  name: 法律
  description: 本目录主要收录与中国多元性别及法律相关的学术文献，涵盖变性人群体的法律地位、婚姻权利及社会保护等多方面议题。例如，其中包括陆俊杰的《性别选择与法律的回应》，该文章探讨了性别选择权的法律保护及变性人权益的确认；官晓薇的论文则分析了台湾在同志人权保障方面的发展与法律变迁，特别是在婚姻平权方面的重要进展；同时《2021年中国跨性别权利公众舆论报告》提供了中国跨性别者在公众认知与社会接受度方面的具体数据，揭示了跨性别者在职场及家庭中的现状及挑战。这部分资料不仅为研究多元性别提供了法律视角，同时也反映了社会对性别认同及权利保障的变化与期待。通过对跨性别者的生存现状进行深入分析，这些文献强调了法律与政策制定的必要性，以促进更广泛的性别认同与社会接纳。
政府及官方组织文件:
  name: 政府及官方组织文件
  description: 本目录收录了与跨性别相关的政府及官方组织文件，包括中国大陆、加拿大、港澳台、美国以及联合国等地区和组织的相关政策和文件。「官方组织」指拥有接近「政府」地位和影响力，但不属于「政府」的国际性组织，在本版块中只指代联合国及其下属机构。这些资料为跨性别群体提供了法律政策、社会环境的背景信息，帮助人们理解不同地区的现状和对跨性别者的支持程度。
政府及官方组织文件/中国大陆:
  name: 中国大陆
  description: 该目录包含与中国大陆政府及官方组织相关的跨性别法律文件和政策资料。提供各种宣传资料、政府报告及法律文书，有助于深入了解国家法律政策对跨性别群体的影响和支持。
政府及官方组织文件/其他地区:
  name: 其他地区
  description: 该目录包含与跨性别政策和法律相关的政府及官方组织文件，旨在为跨性别者提供合法权益方面的指导和支持，特别是在其他地区的实施情况和伴侣制度的适用性。
政府及官方组织文件/加拿大:
  name: 加拿大
  description: 本目录收录有关加拿大的政府及官方组织对跨性别者的政策、法律及其相关文件，旨在提供关于跨性别者权益保障、健康医疗服务以及社会支持等方面的官方信息和资源。
政府及官方组织文件/港澳台:
  name: 港澳台
  description: '该目录收录了来自香港与多元性别相关的政府及官方文件，其内容涉及跨性别者的权利、法律政策、医疗资源及社会环境记录。在《性别承认咨询文件》的意见书中，关注女性暴力协会提出性别承认应该是一项基本人权，强调跨性别者的选择权应当受到尊重，并详细讨论香港是否应设立性别承认制度。文中提到香港的性别问题并非二元对立，亟需关注性别少数群体的权利。该文件中提出的在法律上保护跨性别者的建议，强调应当设立新法规以确保其权利被充分保障，并提出了对性别认可的多样性的理解。


    另一个文件关于2014年婚姻修订条例草案的公听会，记录了针对变性手术及跨性别人士的讨论，揭示了公众对变性手术的误解与关注。袁维昌医生在会上阐述了变性手术的重要性与合理性，同时也讨论了变性人士面临的法律与社会压力。


    此外，关于全国大专院校运动会的跨性别学生运动员参与政策，目录中提供了一份政策草案，强调了保障跨性别运动员权益的重要性，主要内容围绕参与资格的标准及保障机制，以确保参与者能够在公平与尊重的环境中参赛。


    目录中还包含了匹兹堡警察局与LGBTQIA性少数族群的互动记录，揭示社区对警方的失望及对性工作者和跨性别者权益的迫切关注。同时还有关于性别不安的治疗方法的讨论，探讨心理健康和医疗资源的现状。

    该目录还收录了香港性文化学会关于性别承认的公众咨询问答，阐释了性别承认的法律问题，并提供了社会对变性人的接受度的分析，通过这些文件，展示了香港在跨性别法律承认与医疗支持方面的努力与挑战。'
政府及官方组织文件/美国:
  name: 美国
  description: 本目录收录了来自美国的政府及官方组织关于跨性别相关政策和法律的文件，旨在提供对跨性别者权益和法律保护的官方信息和指南。
政府及官方组织文件/联合国:
  name: 联合国
  description: 本目录收录了与联合国相关的官方文件，旨在提供跨性别人士在全球范围内受到的法律保护和人权关注的资讯。这些文件将有助于了解各国在跨性别相关议题上的政策和承诺。
文学作品和艺术创作:
  name: 文学作品和艺术创作
  description: 本部分收录一切形式的跨儿文学艺术创作。无论是发布于互联网某个阴暗角落的「变性人」自传，还是形式晦涩、发人深省的诗歌电影，均可收录在本版块。，涵盖了多种形式的表达，包括小说、漫画、纪实作品、自传和诗歌等。
文学作品和艺术创作/其他:
  name: 其他
  description: 该目录收录了一系列与多元性别相关的文学作品和艺术创作，旨在展现酷儿文化和跨性别议题在当代艺术中的重要性。目录中的作品涵盖了多个方面，包括2024年威尼斯双年展上素人艺术家的展评，此展评关注了未经主流认可的艺术创作，探索了身份和表现的多重性。吴曾的《镜头切开身份》作品也在其中，深入剖析了艺术创作如何与酷儿文化交织，提出了对身份认同和表达的反思。报告涉及的巴特勒作品集则引发对性别和权力关系的深刻探讨，鼓励观众在艺术中寻找自我认知。海伦·马尔滕与亚力汉德罗·西塞科的作品，通过艺术介入的方式揭示了社会问题的复杂性，展示了艺术在推动社会变革中的力量。总之，该目录不仅仅是艺术作品的合集，也是对多元性别现象的深刻洞察与探索。
文学作品和艺术创作/图像:
  name: 图像
  description: 该目录收录了与跨性别主题相关的摄影、绘画等图片作品。
文学作品和艺术创作/小说:
  name: 小说
  description: 本目录收录与跨性别相关的小说作品，涵盖了跨性别者的生活经历、情感纠葛及自我认同等主题。作品通过文学的方式，表达了跨性别者的独特声音与故事，旨在提高社会对这一群体的理解与关注。注：本目录收录的文档仅为部分小说以及评论，更多请访问
    性转小说档案 <https://novel.transchinese.org/>、 <https://xnovel.transchinese.org/> 和
    <https://unovel.transchinese.org/> 获取。
文学作品和艺术创作/纪实作品:
  name: 纪实作品
  description: 该目录收录与跨性别相关的纪实作品，展现跨性别者的真实生活与经历。这些作品不仅反映了个人故事，还呈现了对于社会现象的深刻洞察，包括对身份认同、过渡过程及社会接受度等话题的探索。
文学作品和艺术创作/自传:
  name: 自传
  description: 该目录收录与跨性别相关的自传性文学作品，展示跨性别者的生命故事与过渡经历。自传不仅反映个人的成长与探索，还记录了在社会环境中的真实挑战与心路历程，具有重要的文学价值和社会意义。
文学作品和艺术创作/诗歌:
  name: 诗歌
  description: 本目录收录与跨性别主题相关的诗歌作品，旨在通过文学的方式表达跨性别人群的内心世界与情感历程。这些作品反映了跨性别个体在社会、文化背景下的经历和感受，展示了多样的艺术表现形式。
文学作品和艺术创作/音频影像:
  name: 音频影像
  description: 本目录收录了与跨性别相关的音频影像作品，包括艺术中心与国际美术馆合作的项目。这些作品展示了跨性别艺术家的创作，反映了其独特的视角和经历。
杂志及新闻报道:
  name: 杂志及新闻报道
  description: 本目录包含关于中国大陆、海外及港澳台地区的跨性别相关杂志与新闻报道，二级分类按照发布的报纸杂志所在地区区分。旨在汇集各地对跨性别话题的不同视角与声音，提供相关信息和资源。此处主要收集传统媒体以及
    PDF 文档或图片形式的新闻报道，例如杂志、剪报等。网页新闻报道请访问 <https://news.transchinese.org>，包含数千个相关网页。
杂志及新闻报道/中国大陆:
  name: 中国大陆
  description: 这一目录收录了来自中国大陆的杂志和新闻报道，涵盖了跨性别群体的各种生活与社会现象，提供了真实的视角和声音，展示了跨性别者在社会中所面临的挑战与成就。
杂志及新闻报道/海外:
  name: 海外
  description: 此目录包含与跨性别相关的国际杂志和新闻报道，旨在分享海外跨性别群体的生活、挑战和成就。这些报道和文章提供了宝贵的视角，加深公众对跨性别议题的理解，促进社会包容。
杂志及新闻报道/港澳台:
  name: 港澳台
  description: 本目录收录与港澳台地区相关的跨性别报道与杂志内容，包括对跨性别者的生活、法律、医疗等多方面的报道，旨在宣传和提高社会对跨性别问题的认知与理解。
社群及NGO文件:
  name: 社群及NGO文件
  description: 本部分可收录的内容较为广泛。无论是如北京同志中心、同语这样的 NGO 出具的调查报告、教程指南，还是跨儿社群某论坛上由志愿者写作的 HRT
    指南、出柜指南等，甚至是「女装」或自我探索类教程，均可收录在本版块内。这一目录也包括各类医疗体系、学校和社群的相关资料。这些信息有助于了解支持跨性别人士的组织资源及环境。
社群及NGO文件/其他组织文件:
  name: 其他组织文件
  description: 这一目录包含关于跨性别群体的统计报告和资料指南，旨在提供有效的资源和数据支持，帮助人们更好地理解和关注跨性别群体的需求与现状。
社群及NGO文件/医院和医疗体系:
  name: 医院和医疗体系
  description: 此目录收录了与跨性别相关的医院及医疗体系信息，例如医疗资源、医院政策及医疗经验分享等。这些资料可帮助跨性别者了解医疗服务的可获得性和具体体验。
社群及NGO文件/学校:
  name: 学校
  description: 该目录包含与学校及教育相关的跨性别社群和非政府组织的文件。这些文件可能涵盖学校内的支持资源、跨性别学生的权益保护信息、教育政策的变革等内容，以推动对跨性别群体的理解和接纳。
社群及NGO文件/手册指南:
  name: 手册指南
  description: '该目录下收录的资料主要是关于跨性别医疗照护、法律政策和社会环境的内容，致力于为跨性别群体提供实用信息与支持。，《2022版跨性别医疗照护手册》是一份综合性的指南，为跨性别个体在医疗体系中的经历提供了详细的理解，并涵盖激素治疗、手术选择及法律权益等方面的重要信息。手册通过多位跨性别人士的真实故事，揭示了他们可能面临的现实挑战，借此希望提高医疗界的敏感性和包容性。该手册汇集了多个医疗资源链接，帮助跨性别个体更好地获得所需的支持与服务。


    《Gossip Boys and Girls》则为香港的跨性别人士提供了丰富的文化与社会环境探讨，强调跨性别者身份与性倾向的复杂性，并反映了他们在传统文化下所遭遇到的挣扎与误解。它不仅试图促进对跨性别群体的理解，还讨论了相关个案以展示文化背景对跨性别个体的影响。《BSA指南：有关性别认同问题的投诉》为公众和媒体提供了关于性别认同的重要指导，指明媒体在报道相关话题时需保持敏感与谨慎，确保不再中伤或误解跨性别群体。


    文献中频繁提及的激素替代疗法（HRT）相关资料则深入探讨了为跨性别女性提供的激素治疗方式与考虑事项，确保患者在接受治疗时能具备充分的知识与准备。而数字暴力的报道指南则着重于如何在新闻报道中处理针对性别群体的暴力问题，强调了媒体在面对这些敏感话题时的道德责任。


    从《社群指南：性少数性工作者经历的恐同与恐跨性别》到《反暴力手册》，目录内容涵盖了跨性别者所面临的多重社会问题与健康挑战，明确了法律改革与社会支持的重要性。整体而言，该目录不仅着眼于医疗与法律的交集，更强调跨性别群体在社会环境中的生存状况，通过各种手册与指南促进理解与积极变革，为跨性别个体提供支持与希望。'
社群及NGO文件/生活与性体验:
  name: 生活与性体验
  description: 该目录包含关于生活与性体验的多个文件，旨在为跨性别者提供实用的知识与技能，促进性健康与身体认知。文件内容涵盖了肌肉控制、性愉悦技巧、身体认知、心理适应等方面。具体来说，包括PC肌的收缩分解、如何进行会阴按摩、乳首的开发技巧以及伪声与伪娘训练的方法。这些内容不仅帮助跨性别者了解和掌控自己的身体，还提供了一系列实践指导，旨在支持他们的生活质量与性体验。其中还涉及如何理解和参与性愉悦的多样性实践，秉持对个人身体和性别身份的尊重与认同。
社群及NGO文件/社群讨论:
  name: 社群讨论
  description: 该目录包含了与跨性别社群相关的组织和非政府组织（NGO）的信息，包括中国大陆及海外的社群动态和资源。
社群及NGO文件/统计报告:
  name: 统计报告
  description: 本目录包含关于跨性别群体及多元性别相关统计报告和研究的文件，旨在提供深入分析和数据支持，以帮助了解跨性别及多元性别者在各种社会环境下的生活和面临的挑战。，《2012年父母对跨性别青少年的支持影响报告》探讨了家庭支持如何影响跨性别青少年的心理健康和生活满意度，强调了接纳对青少年情绪与社会适应的重要性。《2013年扭转治疗调查报告》深入分析了扭转治疗对同志群体的心理社会影响，强调这种治疗的无效性和潜在危害，引发对该治疗必要性的质疑。《2015年亚太催化剂-北京上海跨性别女性性工作者生活状况调查》和《2016年愛滋病預防項目指標調查報告-男跨女跨性别人士》则着重揭示了跨性别性工作者和男跨女跨性别者面对的法律、医疗和社会支持挑战，尤其在健康服务和生活条件方面的困境。《2017年中国跨性别人口综合调查报告》则是全国性统计调查，旨在通过数据分析促进针对跨性别者权利的社会认识与政策倡导。接下来的报告如《2020年跨性别就业与职场调查报告》和《2021全国跨性别健康调研报告》，聚焦于跨性别者在职场以及健康方面的状况，揭示了就业歧视和医疗服务不足的问题，从而为更包容的社会政策提供建议。《2023年行政院多元性别生活状况调查研究报告》分析了多元性别群体在台湾的生活现状，强调了社会支持的重要性以及对歧视的应对机制。《我想保留天生的模样_美国双性儿童遭受的非医疗必要手术》和《跨性别人士在保安部门遇到的性骚扰》强调了特定人群（如双性儿童和跨性别者）在社会与法律环境中的特定挑战，提出了对改善政策和社会认知的需求。这些报告对理解跨性别与多元性别群体的现状至关重要。
