name: 中国大陆
description: 这一目录收录了来自中国大陆的杂志和新闻报道，涵盖了跨性别群体的各种生活与社会现象，提供了真实的视角和声音，展示了跨性别者在社会中所面临的挑战与成就。
curator: ''
source: ''
tags:
- 跨性别
- 中国大陆
- 杂志
- 新闻报道
- 社会现象
license: ''
files:
- name: 18岁男孩在快捷酒店里接受变性手术
  filename: 18岁男孩在快捷酒店里接受变性手术.pdf
  type: document
  format: PDF Document
  size: 1689844
  md5: 6ce509f72ab91e5c526d0712891bd2c6
  page: 18岁男孩在快捷酒店里接受变性手术_page.md
  visitors: 39
- name: 2012年小学性教育新思路_李青
  filename: 2012年小学性教育新思路_李青.pdf
  type: document
  format: PDF Document
  size: 444075
  md5: 02ba197a68a0cbe9b630584885414505
  page: 2012年小学性教育新思路_李青_page.md
  visitors: 2
- name: 2013年上海骄傲节宣传稿
  filename: 2013年上海骄傲节宣传稿.pdf
  type: document
  format: PDF Document
  size: 599556
  md5: 0d0a0e4d71cd25e655ee2d59b9878c22
  page: 2013年上海骄傲节宣传稿_page.md
  visitors: 1
- name: 2014__使他从孝子变性为孝女
  filename: 2014__使他从孝子变性为孝女.pdf
  type: document
  format: PDF Document
  size: 328847
  md5: 2a9add42264f120759ecc495c2940d4d
  page: 2014__使他从孝子变性为孝女_page.md
  visitors: 9
- name: 2014_年第一版_酷拉时报
  filename: 2014_年第一版_酷拉时报.pdf
  type: document
  format: PDF Document
  size: 5473417
  md5: cd79024816609d7701c2a0e843a17b70
  page: 2014_年第一版_酷拉时报_page.md
- name: 2017中国跨性别群体生存现状调查报告发布_北京同志中心
  filename: 2017中国跨性别群体生存现状调查报告发布_北京同志中心.pdf
  type: document
  format: PDF Document
  size: 776338
  md5: 8990698524f50fae02c6d760a10bf9fe
  page: 2017中国跨性别群体生存现状调查报告发布_北京同志中心_page.md
  visitors: 15
- name: Les+双月刊2007年09月
  filename: Les+双月刊2007年09月.pdf
  type: document
  format: PDF Document
  size: 3063011
  md5: d73aff9a0356a77ccab8af1a014dcdc3
  page: Les+双月刊2007年09月_page.md
  visitors: 2
- name: 一口吞下18粒右美沙芬，他瘫在床上青少年滥用药品现象调查_2023_
  filename: 一口吞下18粒右美沙芬，他瘫在床上青少年滥用药品现象调查_2023_.pdf
  type: document
  format: PDF Document
  size: 2740146
  md5: 75839c68a331fa7ab206f6d7fa23f977
  page: 一口吞下18粒右美沙芬，他瘫在床上青少年滥用药品现象调查_2023__page.md
  visitors: 10
- name: 不想让男孩长成“伪娘”家庭教育要从娃娃抓起_晚报
  filename: 不想让男孩长成“伪娘”家庭教育要从娃娃抓起_晚报.pdf
  type: document
  format: PDF Document
  size: 1151109
  md5: 321590cef1bf0e68c4d9b0c6a6a4ebee
  page: 不想让男孩长成“伪娘”家庭教育要从娃娃抓起_晚报_page.md
  visitors: 24
- name: 中国社会工作中国2016年第1期
  filename: 中国社会工作中国2016年第1期.pdf
  type: document
  format: PDF Document
  size: 23568862
  md5: 83587f8dcbe17bcd7be51c27f028f68b
  page: 中国社会工作中国2016年第1期_page.md
  visitors: 6
- name: 中国第一变性人自述_陕西工人报_2003
  filename: 中国第一变性人自述_陕西工人报_2003.pdf
  type: document
  format: PDF Document
  size: 9749531
  md5: a02001c63a6e3dfb65df0ae533a8536e
  page: 中国第一变性人自述_陕西工人报_2003_page.md
  visitors: 6
- name: 中国首位变性人状告医院始末_李玉林
  filename: 中国首位变性人状告医院始末_李玉林.pdf
  type: document
  format: PDF Document
  size: 728924
  md5: 32dc3f16aebe8788fbade96cc7294f31
  page: 中国首位变性人状告医院始末_李玉林_page.md
  visitors: 3
- name: 中國版河莉秀欲造子宮生子
  filename: 中國版河莉秀欲造子宮生子.pdf
  type: document
  format: PDF Document
  size: 2156104
  md5: 5a7142044488434c59a40ebd23386e8c
  page: 中國版河莉秀欲造子宮生子_page.md
  visitors: 4
- name: 人民日报_1992_首例女变男变性手术成功
  filename: 人民日报_1992_首例女变男变性手术成功.pdf
  type: document
  format: PDF Document
  size: 1902043
  md5: e76c1852dccd0515cced27e8d103af7b
  page: 人民日报_1992_首例女变男变性手术成功_page.md
  visitors: 15
- name: 人民日报_1993_我国变性手术达到世界先进水平
  filename: 人民日报_1993_我国变性手术达到世界先进水平.pdf
  type: document
  format: PDF Document
  size: 1848295
  md5: 34eea651a3753f5fe651fdd566cfae59
  page: 人民日报_1993_我国变性手术达到世界先进水平_page.md
  visitors: 6
- name: 人民日报_从性别观说开去（2005年11月12日_第7版_副刊）
  filename: 人民日报_从性别观说开去（2005年11月12日_第7版_副刊）.pdf
  type: document
  format: PDF Document
  size: 282502
  md5: c9e27c6b9a83d7ad94ad87c66692d98f
  page: 人民日报_从性别观说开去（2005年11月12日_第7版_副刊）_page.md
  visitors: 11
- name: 他们在家门口书写生命终章
  filename: 他们在家门口书写生命终章.pdf
  type: document
  format: PDF Document
  size: 1543444
  md5: 2cef04069e6565dc23c620ca34932be2
  page: 他们在家门口书写生命终章_page.md
  visitors: 6
- name: 修好人的另一扇门——性别重塑艰难而火热_时生
  filename: 修好人的另一扇门——性别重塑艰难而火热_时生.pdf
  type: document
  format: PDF Document
  size: 481827
  md5: a31fb87e7d6095a9db042a8802d215fb
  page: 修好人的另一扇门——性别重塑艰难而火热_时生_page.md
  visitors: 4
- name: 做变性手术须年满20岁中国新闻
  filename: 做变性手术须年满20岁中国新闻.pdf
  type: document
  format: PDF Document
  size: 215633
  md5: 3639d1dc5c32b5b3abb16f4a9b2571d5
  page: 做变性手术须年满20岁中国新闻_page.md
  visitors: 2
- name: 冷杉RECORD｜不完美跨儿：病人、斗士与谎言_404文库
  filename: 冷杉RECORD｜不完美跨儿：病人、斗士与谎言_404文库.pdf
  type: document
  format: PDF Document
  size: 19334628
  md5: 21f4625b5ada1d7b9c9e173bbb99fa60
  page: 冷杉RECORD｜不完美跨儿：病人、斗士与谎言_404文库_page.md
  visitors: 8
- name: 变性人、劳教者、在校大学生等今天起可登记结婚_中国新闻网_2003
  filename: 变性人、劳教者、在校大学生等今天起可登记结婚_中国新闻网_2003.pdf
  type: document
  format: PDF Document
  size: 628921
  md5: 05f16783fc1cb3c7c21d8e2da1ea81ec
  page: 变性人、劳教者、在校大学生等今天起可登记结婚_中国新闻网_2003_page.md
  visitors: 1
- name: 变性人可否结婚_广西政法报_2003年
  filename: 变性人可否结婚_广西政法报_2003年.pdf
  type: document
  format: PDF Document
  size: 54480
  md5: 5845eb8bbb472ff1c41f80d287660a81
  page: 变性人可否结婚_广西政法报_2003年_page.md
  visitors: 4
- name: 变性人户口被许可易性的法律意义_本报记者_李青_法制日报
  filename: 变性人户口被许可易性的法律意义_本报记者_李青_法制日报.pdf
  type: document
  format: PDF Document
  size: 21437
  md5: e058de62be115bc24b3876dc299d4012
  page: 变性人户口被许可易性的法律意义_本报记者_李青_法制日报_page.md
  visitors: 4
- name: 变性人有权以新性别结婚_人民日报
  filename: 变性人有权以新性别结婚_人民日报.pdf
  type: document
  format: PDF Document
  size: 678928
  md5: 0a757310ea245c23a95b013e6b7fd041
  page: 变性人有权以新性别结婚_人民日报_page.md
  visitors: 2
- name: 变性后利用色相行骗安徽变性第一人获刑三年
  filename: 变性后利用色相行骗安徽变性第一人获刑三年.pdf
  type: document
  format: PDF Document
  size: 1686719
  md5: 561f296b9ea18e799df3ee558ea683cf
  page: 变性后利用色相行骗安徽变性第一人获刑三年_page.md
  visitors: 2
- name: 国外一准变性人参加男足
  filename: 国外一准变性人参加男足.PDF
  type: document
  format: PDF Document
  size: 3704285
  md5: d5a43109f2cb172ad84e8c6f5e78a07a
  page: 国外一准变性人参加男足_page.md
  visitors: 2
- name: 对变性人该关注什么_-_中国妇女报_-_2004
  filename: 对变性人该关注什么_-_中国妇女报_-_2004.pdf
  type: document
  format: PDF Document
  size: 85020
  md5: 6116097118c6217267a13ce7879066d5
  page: 对变性人该关注什么_-_中国妇女报_-_2004_page.md
  visitors: 14
- name: 异装癖，或缘于压力过大_卫生报
  filename: 异装癖，或缘于压力过大_卫生报.pdf
  type: document
  format: PDF Document
  size: 445651
  md5: a8d57aa44c56432d7ede09c49e6d6dad
  page: 异装癖，或缘于压力过大_卫生报_page.md
  visitors: 4
- name: 拯救可橙：被父母强送矫治的跨性别者
  filename: 拯救可橙：被父母强送矫治的跨性别者.pdf
  type: document
  format: PDF Document
  size: 2904100
  md5: cc18a34320ff30ec3b6bdaaf2b58ef62
  page: 拯救可橙：被父母强送矫治的跨性别者_page.md
  visitors: 15
- name: 日本将增设“中性厕所”_如厕小心走错门_新视听_2015
  filename: 日本将增设“中性厕所”_如厕小心走错门_新视听_2015.pdf
  type: document
  format: PDF Document
  size: 1606879
  md5: 37c7f0fa8ca465a235670151e53c791a
  page: 日本将增设“中性厕所”_如厕小心走错门_新视听_2015_page.md
  visitors: 1
- name: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇
  filename: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇.pdf
  type: document
  format: PDF Document
  size: 22098
  md5: c6f263e699ce769269a20e0cf38a9be2
  page: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇_page.md
- name: 法治时空_变性人先色诱再抢劫
  filename: 法治时空_变性人先色诱再抢劫.pdf
  type: document
  format: PDF Document
  size: 842641
  md5: 2767d0d3ae0a123dfa9d2741e9e7a0b6
  page: 法治时空_变性人先色诱再抢劫_page.md
  visitors: 1
- name: 烦恼多多话变性_项力
  filename: 烦恼多多话变性_项力.pdf
  type: document
  format: PDF Document
  size: 884971
  md5: 5e9d3c9d91418594f09b2d4388c00782
  page: 烦恼多多话变性_项力_page.md
- name: 第39届飞天奖颁奖典礼分析与报道
  filename: 第39届飞天奖颁奖典礼分析与报道.pdf
  type: document
  format: PDF Document
  size: 311575
  md5: ec04069151a46c9c6c4ab8a205962c89
  page: 第39届飞天奖颁奖典礼分析与报道_page.md
  visitors: 1
- name: 第六届北京酷儿影展闭幕新闻稿_2013
  filename: 第六届北京酷儿影展闭幕新闻稿_2013.pdf
  type: document
  format: PDF Document
  size: 104958
  md5: b98606526879f6f555b129c2fad4a4e0
  page: 第六届北京酷儿影展闭幕新闻稿_2013_page.md
  visitors: 1
- name: 被殴打、遭虐待，曝光特训学校的暗面
  filename: 被殴打、遭虐待，曝光特训学校的暗面.pdf
  type: document
  format: PDF Document
  size: 24598590
  md5: b15a7d699886e28cc5751ea066c0d627
  page: 被殴打、遭虐待，曝光特训学校的暗面_page.md
  visitors: 2
- name: 西方的变性热_王克强
  filename: 西方的变性热_王克强.pdf
  type: document
  format: PDF Document
  size: 73066
  md5: 3366131a1785efee8612229e92aec724
  page: 西方的变性热_王克强_page.md
  visitors: 2
- name: 谁是中国首例变性人_谷雨生
  filename: 谁是中国首例变性人_谷雨生.pdf
  type: document
  format: PDF Document
  size: 1143144
  md5: 7fca112a0832ee2a0620995d0585cfc0
  page: 谁是中国首例变性人_谷雨生_page.md
  visitors: 1
- name: 走上T台刘婷最美蝶变
  filename: 走上T台刘婷最美蝶变.pdf
  type: document
  format: PDF Document
  size: 2283814
  md5: ad4adad9db1001df01021cbbe4e5591c
  page: 走上T台刘婷最美蝶变_page.md
  visitors: 5
- name: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士
  filename: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士.pdf
  type: document
  format: PDF Document
  size: 1133665
  md5: fdbe9d47b7c7b5efe311480409dc1ac5
  page: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士_page.md
  visitors: 5
- name: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9
  filename: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9.pdf
  type: document
  format: PDF Document
  size: 3508058
  md5: 83741baf3e0db3c8329c563d722b502c
  page: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9_page.md
  visitors: 3
- name: 跨性别者被电击治疗_医院否认有过错_中华网
  filename: 跨性别者被电击治疗_医院否认有过错_中华网.pdf
  type: document
  format: PDF Document
  size: 5716693
  md5: 048c036c08200cfb3975b7720a5fba67
  page: 跨性别者被电击治疗_医院否认有过错_中华网_page.md
  visitors: 10
subdirs: []
