name: 政府及官方组织文件
description: 本目录收录了与跨性别相关的政府及官方组织文件，包括中国大陆、加拿大、港澳台、美国以及联合国等地区和组织的相关政策和文件。「官方组织」指拥有接近「政府」地位和影响力，但不属于「政府」的国际性组织，在本版块中只指代联合国及其下属机构。这些资料为跨性别群体提供了法律政策、社会环境的背景信息，帮助人们理解不同地区的现状和对跨性别者的支持程度。
curator: ''
source: ''
tags:
- 政府文件
- 政策
- 法律
- 跨性别
- 社会环境
- 中国大陆
- 加拿大
- 港澳台
- 美国
- 联合国
license: ''
files: []
subdirs:
- 中国大陆
- 其他地区
- 加拿大
- 港澳台
- 美国
- 联合国
