name: 变成女孩子声音
description: 本目录收录了关于变成女孩子声音的相关资料，包括汉化文本及声音训练的CD资源。这对于希望通过声音转变更好表达自我的跨性别人士具有重要的参考价值。
curator: ''
source: ''
tags:
- 跨性别
- 声音训练
- 女性化
- 汉化
- 资源分享
license: ''
files:
- name: 变成女孩子声音（汉化文本）
  filename: 变成女孩子声音（汉化文本）.txt
  type: document
  format: Plain Text
  size: 34908
  md5: cc34982b9b20e8a4dc11a6644749a8f0
  page: 变成女孩子声音（汉化文本）_page.md
  visitors: 404
subdirs:
- 《女の子の声になろう!》CD
- 女の子の声になろう!
