name: 中国大陆跨性别相关法规与政府文件
description: '目录路径为“./政府及官方组织文件/中国大陆”的档案汇集了一系列与中国大陆的法律法规、政策规范和管理文件有关的内容。这些文件中涉及的主题多样，包括婚姻法在跨性别议题上的适用性、精神卫生管理规范、中国精神卫生法的具体内容、多学科诊疗共识及标准、中国大陆的精神障碍分类与诊断标准、以及公安机关在居民身份证与户籍管理中的操作规范。这些内容揭示了跨性别者在家庭和法律背景下遭遇的复杂挑战，也展示了中国在精神卫生、医疗管理和户籍政策方面的制度演变。一个重要的讨论点是跨性别者在面对婚姻法局限性的故事记录。一位女性发现丈夫未经同意进行了变性手术，引发了对婚姻关系法律地位的质疑，这反映了性别认同对婚姻制度的冲击和法律的局限性。另一份文件，则是公安部关于如何变更公民性别登记的文件，根据手术后的性别变更要求提供法律路径，标志着在中国大陆政策层面变性人的地位变迁。

  关于精神卫生管理及法律，文件详细探讨了精神疾病的管理规范和法律条文，强调了提高患者跟踪和服务质量的重要性，明确了精神卫生领域的法律保障框架以及精神健康工作的社会责任。这些文件说明了中国在精神卫生领域的关注和努力提升管理标准及服务水平的国家意图。总览这些档案，可见中国大陆在面对社会多元性别、精神健康和法治完善方面的长期发展和政策变化。'
curator: ''
source: ''
tags:
- 跨性别
- 婚姻法
- 精神卫生管理
- 法律政策
- 社会背景
- 户籍管理
- 精神健康
- 多元性别
- 中国大陆
- 政策文件
license: ''
files:
- name: 丈夫私自做了变性手术，婚姻关系合法吗？
  filename: 丈夫私自做了变性手术，婚姻关系合法吗？.md
  type: webpage
  format: Markdown
  size: 1500
  md5: b390326f199b53b247253cbee156348b
  page: 丈夫私自做了变性手术，婚姻关系合法吗？.md
  visitors: 16
- name: 严重精神障碍管理治疗工作规范_2018年版
  filename: 严重精神障碍管理治疗工作规范_2018年版.md
  type: webpage
  format: Markdown
  size: 1514
  md5: 363d47abd20b01c6f3f9c76fc66d4117
  page: 严重精神障碍管理治疗工作规范_2018年版.md
  visitors: 9
- name: 中华人民共和国精神卫生法文本
  filename: 中华人民共和国精神卫生法文本.md
  type: webpage
  format: Markdown
  size: 32062
  md5: dbc5c11616d6d7bbb472fde7679ca5db
  page: 中华人民共和国精神卫生法文本.md
  visitors: 1
- name: 中国易性症多学科诊疗专家共识收稿
  filename: 中国易性症多学科诊疗专家共识收稿.md
  type: webpage
  format: Markdown
  size: 180
  md5: 146c747ae58cdd7c3742fe4c4f8e9ee6
  page: 中国易性症多学科诊疗专家共识收稿.md
  visitors: 7
- name: 中国精神障碍分类及诊断标准_第三版
  filename: 中国精神障碍分类及诊断标准_第三版.md
  type: webpage
  format: Markdown
  size: 5862
  md5: df9c2aa540c473e76997814d819d89be
  page: 中国精神障碍分类及诊断标准_第三版.md
  visitors: 14
- name: 公安部三局关于公民实施变性手术后变更户口登记性别项目有关问题的批复
  filename: 公安部三局关于公民实施变性手术后变更户口登记性别项目有关问题的批复.md
  type: webpage
  format: Markdown
  size: 993
  md5: 4950d673374459c262c7ecb95c74510e
  page: 公安部三局关于公民实施变性手术后变更户口登记性别项目有关问题的批复.md
  visitors: 3
- name: 公安部关于印发《户口居民身份证管理工作规范（试行）》的通知
  filename: 公安部关于印发《户口居民身份证管理工作规范（试行）》的通知.md
  type: webpage
  format: Markdown
  size: 33184
  md5: 8338ad9e620e1330f6d7fa8e24bec9c8
  page: 公安部关于印发《户口居民身份证管理工作规范（试行）》的通知.md
  visitors: 3
- name: 公安部对变性手术后户口性别变更的批复_2008
  filename: 公安部对变性手术后户口性别变更的批复_2008.md
  type: webpage
  format: Markdown
  size: 1403
  md5: 4edd9e699f23a6863ece4507c757a488
  page: 公安部对变性手术后户口性别变更的批复_2008.md
  visitors: 1
- name: 公安部治安管理局关于公民手术变性后变更户口登记性别项目有关问题的批复
  filename: 公安部治安管理局关于公民手术变性后变更户口登记性别项目有关问题的批复.md
  type: webpage
  format: Markdown
  size: 1401
  md5: e0493809fefbd981c5c03053182d830a
  page: 公安部治安管理局关于公民手术变性后变更户口登记性别项目有关问题的批复.md
- name: 关于ICD-11中文版的通知-2018
  filename: 关于ICD-11中文版的通知-2018.md
  type: webpage
  format: Markdown
  size: 2883
  md5: a10dec8d0cc9bab8c0f01465786dda1a
  page: 关于ICD-11中文版的通知-2018.md
  visitors: 1
- name: 关于公民实施变性手术后变更户口登记性别项目有关问题的通知
  filename: 关于公民实施变性手术后变更户口登记性别项目有关问题的通知.md
  type: webpage
  format: Markdown
  size: 1371
  md5: d6b51d760f5ec411cf18cabf5384a5e9
  page: 关于公民实施变性手术后变更户口登记性别项目有关问题的通知.md
  visitors: 2
- name: 关于印发《重性精神疾病管理治疗工作规范（2012_年版）》的通知
  filename: 关于印发《重性精神疾病管理治疗工作规范（2012_年版）》的通知.md
  type: webpage
  format: Markdown
  size: 1514
  md5: 1cb91a4d290658e93ff1edef835f26c9
  page: 关于印发《重性精神疾病管理治疗工作规范（2012_年版）》的通知.md
- name: 关于防止男性青少年女性化的提案_答复的函
  filename: 关于防止男性青少年女性化的提案_答复的函.md
  type: webpage
  format: Markdown
  size: 6581
  md5: 1ba2a9720ab072816d71935ca05ed91b
  page: 关于防止男性青少年女性化的提案_答复的函.md
  visitors: 9
- name: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知
  filename: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知.pdf
  type: document
  format: PDF Document
  size: 846716
  md5: f65e050584da608371edf3c7f8141b79
  page: 卫生部办公厅关于公布首批允许临床应用的第三类医疗技术目录的通知_page.md
  visitors: 1
- name: 变性手术技术管理规范征求意见稿_便函_2009
  filename: 变性手术技术管理规范征求意见稿_便函_2009.pdf
  type: document
  format: PDF Document
  size: 466420
  md5: 3dea8d62c04b66060c8afbaf4febffa0
  page: 变性手术技术管理规范征求意见稿_便函_2009_page.md
  visitors: 5
- name: 变性手术技术管理规范（征求意见稿）_
  filename: 变性手术技术管理规范（征求意见稿）_.md
  type: webpage
  format: Markdown
  size: 4721
  md5: d6e55b236f728f3ca1940ddd18603054
  page: 变性手术技术管理规范（征求意见稿）_.md
  visitors: 2
- name: 变性手术技术管理规范（试行）
  filename: 变性手术技术管理规范（试行）.md
  type: webpage
  format: Markdown
  size: 4768
  md5: 4d5cea579d789be0415b6b2dd8db2a0c
  page: 变性手术技术管理规范（试行）.md
  visitors: 4
- name: 国家《GBT_14396-2016_疾病分类与代码》标准正式发布
  filename: 国家《GBT_14396-2016_疾病分类与代码》标准正式发布.md
  type: webpage
  format: Markdown
  size: 2533
  md5: f130a8f762cf4e8553f8a0ed7b8bd53e
  page: 国家《GBT_14396-2016_疾病分类与代码》标准正式发布.md
  visitors: 6
- name: 国家广播电视总局办公厅关于进一步加强文艺节目及其人员管理的通知
  filename: 国家广播电视总局办公厅关于进一步加强文艺节目及其人员管理的通知.md
  type: webpage
  format: Markdown
  size: 4741
  md5: 5943a93a4ecaaa40a41972261a6c8445
  page: 国家广播电视总局办公厅关于进一步加强文艺节目及其人员管理的通知.md
  visitors: 2
- name: 国家药监局关于药品网络销售禁止清单的复函_2023
  filename: 国家药监局关于药品网络销售禁止清单的复函_2023.md
  type: webpage
  format: Markdown
  size: 1406
  md5: 5a995e199a4808eba4d3402e3e1439b7
  page: 国家药监局关于药品网络销售禁止清单的复函_2023.md
  visitors: 4
- name: 国家限制类技术目录2022_年版
  filename: 国家限制类技术目录2022_年版.pdf
  type: document
  format: PDF Document
  size: 207409
  md5: 8e00050c2184796a5128c76b5e1616a0
  page: 国家限制类技术目录2022_年版_page.md
  visitors: 4
- name: 夫妻婚姻关系与变性手术法律分析_芳芳_2005
  filename: 夫妻婚姻关系与变性手术法律分析_芳芳_2005.md
  type: webpage
  format: Markdown
  size: 1487
  md5: 062fc6d8c32e07ca50e6f98f4c34685f
  page: 夫妻婚姻关系与变性手术法律分析_芳芳_2005.md
  visitors: 7
- name: 广电总局禁止整容变性节目通知_2007
  filename: 广电总局禁止整容变性节目通知_2007.md
  type: webpage
  format: Markdown
  size: 2899
  md5: e1b04afaa208b451c3815c374134b0b4
  page: 广电总局禁止整容变性节目通知_2007.md
  visitors: 1
- name: 性别发育异常中国专家诊疗共识收稿
  filename: 性别发育异常中国专家诊疗共识收稿.md
  type: webpage
  format: Markdown
  size: 262
  md5: 3b9ccf8a5532b281d149bcc6104c573d
  page: 性别发育异常中国专家诊疗共识收稿.md
- name: 性别重置技术临床应用管理规范_2022
  filename: 性别重置技术临床应用管理规范_2022.md
  type: webpage
  format: Markdown
  size: 6944
  md5: 55cb0ff0cf2e67b4c5f63315b68f5fe1
  page: 性别重置技术临床应用管理规范_2022.md
  visitors: 7
- name: 性别重置技术临床应用质量控制指标_2022
  filename: 性别重置技术临床应用质量控制指标_2022.md
  type: webpage
  format: Markdown
  size: 4449
  md5: 0c25d3d82fb8b0e61d54520e77520d8c
  page: 性别重置技术临床应用质量控制指标_2022.md
  visitors: 8
- name: 性别重置技术管理规范_（2017年版）
  filename: 性别重置技术管理规范_（2017年版）.pdf
  type: document
  format: PDF Document
  size: 95763
  md5: 0b55c91c7296e940ddef4111d22954b9
  page: 性别重置技术管理规范_（2017年版）_page.md
  visitors: 11
- name: 教育部关于防止青少年女性化的提案答复_2020
  filename: 教育部关于防止青少年女性化的提案答复_2020.md
  type: webpage
  format: Markdown
  size: 6582
  md5: 9d71bd14e9f812b245b6dbea4e5e2ab5
  page: 教育部关于防止青少年女性化的提案答复_2020.md
  visitors: 1
- name: 整形外科专科医师规范化培训细则试行（上海市试行）
  filename: 整形外科专科医师规范化培训细则试行（上海市试行）.pdf
  type: document
  format: PDF Document
  size: 315632
  md5: 8fd1d6e46c79e4f940d2add346720740
  page: 整形外科专科医师规范化培训细则试行（上海市试行）_page.md
  visitors: 3
- name: 未成年人互联网不健康内容分类与代码_2022
  filename: 未成年人互联网不健康内容分类与代码_2022.md
  type: webpage
  format: Markdown
  size: 2707
  md5: 4a2a5e38b41ba5e86b398fd1f2902ad9
  page: 未成年人互联网不健康内容分类与代码_2022.md
  visitors: 7
- name: 精神障碍诊疗规范_2020年版
  filename: 精神障碍诊疗规范_2020年版.md
  type: webpage
  format: Markdown
  size: 6106
  md5: 47df7191c3063b41a0b56f6fa233d999
  page: 精神障碍诊疗规范_2020年版.md
  visitors: 2
- name: 药品网络销售禁止清单（第一版）（2022_年_11_月制定）
  filename: 药品网络销售禁止清单（第一版）（2022_年_11_月制定）.md
  type: webpage
  format: Markdown
  size: 1857
  md5: 14163684b3b71f333594eab4d6d3fe27
  page: 药品网络销售禁止清单（第一版）（2022_年_11_月制定）.md
  visitors: 9
subdirs:
- 其他文件
- 原文
