name: 《女の子の声になろう!》CD
description: 这是一个介绍如何通过声音训练变成女孩子声音的音频资料，包含了一张名为《女の子の声になろう!》的CD，主要针对希望在声音上进行过渡的跨性别者，提供相关的练习和指导。
curator: ''
source: ''
tags:
- 声音训练
- 跨性别
- 过渡经历
- 女声
- 音频资料
license: ''
files: []
subdirs:
- 女の子の声になろう!
