name: 港澳台
description: 该目录收录有关港澳台地区跨性别社群及非政府组织的信息和资源，旨在为研究和了解这一人群的现状和需求提供支持。
curator: ''
source: ''
tags:
- 跨性别
- 港澳台
- 社群
- NGO
- 资源分享
license: ''
files:
- name: PDF_台灣率先導入性別光譜數位身分證突破傳統性別定義
  filename: PDF_台灣率先導入性別光譜數位身分證突破傳統性別定義.pdf
  type: document
  format: PDF Document
  size: 11608213
  md5: 94ac3efa43abc4980e595d2f04f1754a
  page: PDF_台灣率先導入性別光譜數位身分證突破傳統性別定義_page.md
  visitors: 10
- name: 我不是故意的-_談跨性別青少年
  filename: 我不是故意的-_談跨性別青少年.pdf
  type: document
  format: PDF Document
  size: 205499
  md5: 9de75259f13c60dcfe0de3a0031ec2f2
  page: 我不是故意的-_談跨性別青少年_page.md
  visitors: 23
subdirs: []
