name: 其他地区
description: 该目录包含与跨性别政策和法律相关的政府及官方组织文件，旨在为跨性别者提供合法权益方面的指导和支持，特别是在其他地区的实施情况和伴侣制度的适用性。
curator: ''
source: ''
tags:
- 政策法规
- 法律支持
- 跨性别权益
- 伴侣制度
- 政府文件
license: ''
files:
- name: 2013至2017年平等性结果工作计划报告
  filename: 2013至2017年平等性结果工作计划报告.pdf
  type: document
  format: PDF Document
  size: 635715
  md5: 79ad791abc43d522aba29989d0d9b651
  page: 2013至2017年平等性结果工作计划报告_page.md
  visitors: 2
- name: 2022_主計月刊_公司治理性別平等與永續發展
  filename: 2022_主計月刊_公司治理性別平等與永續發展.pdf
  type: document
  format: PDF Document
  size: 2517042
  md5: 2b39ed6adc5afbabf010d3b02148feed
  page: 2022_主計月刊_公司治理性別平等與永續發展_page.md
- name: 2022年DEIA与健康公平报告
  filename: 2022年DEIA与健康公平报告.pdf
  type: document
  format: PDF Document
  size: 3413576
  md5: 21a5630716918ef6954cecd09fbd4091
  page: 2022年DEIA与健康公平报告_page.md
- name: 2023年维多利亚州反性工作歧视指导方针
  filename: 2023年维多利亚州反性工作歧视指导方针.pdf
  type: document
  format: PDF Document
  size: 5353776
  md5: 99e842814b877a6519ca20989b2ae684
  page: 2023年维多利亚州反性工作歧视指导方针_page.md
- name: 2023彭博性别平等指数报告
  filename: 2023彭博性别平等指数报告.pdf
  type: document
  format: PDF Document
  size: 2972413
  md5: c0bf1b7ecfe493b01ca2e323b8b62d29
  page: 2023彭博性别平等指数报告_page.md
  visitors: 1
- name: 2024-2025课程目录-贝尔维尤学区
  filename: 2024-2025课程目录-贝尔维尤学区.pdf
  type: document
  format: PDF Document
  size: 7111462
  md5: 96392b46ae73be12debb1d06ecb07c9f
  page: 2024-2025课程目录-贝尔维尤学区_page.md
  visitors: 1
- name: PDF_心智能力法令_-_被授权人指南_-_MSF
  filename: PDF_心智能力法令_-_被授权人指南_-_MSF.pdf
  type: document
  format: PDF Document
  size: 1100302
  md5: 4b00d39ee5a01042e08ae2ef50be4b5e
  page: PDF_心智能力法令_-_被授权人指南_-_MSF_page.md
  visitors: 1
- name: PDF_港区伴侣制度_适用手册（第１版）
  filename: PDF_港区伴侣制度_适用手册（第１版）.pdf
  type: document
  format: PDF Document
  size: 1048906
  md5: 36364306eaa5a93db5de40325c6d51b6
  page: PDF_港区伴侣制度_适用手册（第１版）_page.md
- name: 为人权而写_修哈兹·曼南_2016年
  filename: 为人权而写_修哈兹·曼南_2016年.pdf
  type: document
  format: PDF Document
  size: 309256
  md5: 30c120817db09b634649685e8708667d
  page: 为人权而写_修哈兹·曼南_2016年_page.md
- name: 为信仰者提供安全空间与法律保护_维多利亚州2022法案解读
  filename: 为信仰者提供安全空间与法律保护_维多利亚州2022法案解读.pdf
  type: document
  format: PDF Document
  size: 248382
  md5: efe5d83bea61f8b65c6918b11120cdb0
  page: 为信仰者提供安全空间与法律保护_维多利亚州2022法案解读_page.md
- name: 全民就绪计划_费城版_紧急健康准备指南
  filename: 全民就绪计划_费城版_紧急健康准备指南.pdf
  type: document
  format: PDF Document
  size: 919
  md5: 8e0d22b43dbd5e9d46166040bca31504
  page: 全民就绪计划_费城版_紧急健康准备指南_page.md
- name: 加泰罗尼亚政府关于2024年国际LGBTI骄傲日的声明
  filename: 加泰罗尼亚政府关于2024年国际LGBTI骄傲日的声明.pdf
  type: document
  format: PDF Document
  size: 286161
  md5: b7723702b7df5e4ccdf459283ffbd5b0
  page: 加泰罗尼亚政府关于2024年国际LGBTI骄傲日的声明_page.md
- name: 商業道德政策_對歧視騷擾零容忍
  filename: 商業道德政策_對歧視騷擾零容忍.pdf
  type: document
  format: PDF Document
  size: 306678
  md5: 997105fcdb6d5b4aedd7b066c8993468
  page: 商業道德政策_對歧視騷擾零容忍_page.md
- name: 多元化及包容性补助金申请指南
  filename: 多元化及包容性补助金申请指南.pdf
  type: document
  format: PDF Document
  size: 347489
  md5: 15f0bd9e18d1e9d69fc55a2118b3ae74
  page: 多元化及包容性补助金申请指南_page.md
- name: 孟加拉跨性别者权益捍卫者修哈兹•曼南讲话记录
  filename: 孟加拉跨性别者权益捍卫者修哈兹•曼南讲话记录.pdf
  type: document
  format: PDF Document
  size: 176232
  md5: 16feb924115e94449ac45b7b0c75042e
  page: 孟加拉跨性别者权益捍卫者修哈兹•曼南讲话记录_page.md
- name: 波特兰公立学校2023-2024学生权利与责任手册
  filename: 波特兰公立学校2023-2024学生权利与责任手册.pdf
  type: document
  format: PDF Document
  size: 2206805
  md5: 50dc831bf44011b474a17db8543e029c
  page: 波特兰公立学校2023-2024学生权利与责任手册_page.md
- name: 澳大利亚LGBTIQ社区家庭暴力报告
  filename: 澳大利亚LGBTIQ社区家庭暴力报告.pdf
  type: document
  format: PDF Document
  size: 193568
  md5: 37e4f56fe135a1c84ace652a830e029e
  page: 澳大利亚LGBTIQ社区家庭暴力报告_page.md
  visitors: 1
- name: 瑞士驻华大使馆_多样性与身份认同_公共外交活动手册
  filename: 瑞士驻华大使馆_多样性与身份认同_公共外交活动手册.pdf
  type: document
  format: PDF Document
  size: 13358313
  md5: 21fe98b794097ab1ab431e0284befaf6
  page: 瑞士驻华大使馆_多样性与身份认同_公共外交活动手册_page.md
  visitors: 1
- name: 穆鲁玛郡协调访问口头发布表-2024
  filename: 穆鲁玛郡协调访问口头发布表-2024.pdf
  type: document
  format: PDF Document
  size: 569607
  md5: 03e50ac191722bf2ab3d3a7f1594d901
  page: 穆鲁玛郡协调访问口头发布表-2024_page.md
- name: 维多利亚州变更或压制实践禁止法2021年度解读
  filename: 维多利亚州变更或压制实践禁止法2021年度解读.pdf
  type: document
  format: PDF Document
  size: 810816
  md5: 46ec9d3eaee31716fc5f9ff3b8db3755
  page: 维多利亚州变更或压制实践禁止法2021年度解读_page.md
- name: 罗氏集团2021雇佣政策与多元包容性报告
  filename: 罗氏集团2021雇佣政策与多元包容性报告.pdf
  type: document
  format: PDF Document
  size: 2430020
  md5: 576de994c0995ae78368586d8aaed457
  page: 罗氏集团2021雇佣政策与多元包容性报告_page.md
  visitors: 1
- name: 行政院主計總處性別平等推動計畫111-114年報告
  filename: 行政院主計總處性別平等推動計畫111-114年報告.pdf
  type: document
  format: PDF Document
  size: 467764
  md5: 974ed43c7311ca6de632595f9288357f
  page: 行政院主計總處性別平等推動計畫111-114年報告_page.md
- name: 邁向平等_蘇格蘭護理和社會工作服務報告_2011-2013
  filename: 邁向平等_蘇格蘭護理和社會工作服務報告_2011-2013.pdf
  type: document
  format: PDF Document
  size: 1234567
  md5: 7dac320ad2516dc66f63b82cc232c5b6
  page: 邁向平等_蘇格蘭護理和社會工作服務報告_2011-2013_page.md
subdirs: []
